/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zhuoting_health_util_Crc16Util */

#ifndef _Included_com_zhuoting_health_util_Crc16Util
#define _Included_com_zhuoting_health_util_Crc16Util
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zhuoting_health_util_Crc16Util
 * Method:    makeCRC
 * Signature: ([BI)B
 */
JNIEXPORT jbyte JNICALL Java_com_zhuoting_health_util_Crc16Util_makeCRC
  (JNIEnv *, jobject, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
