/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zhuoting_health_util_Crc16Util */

#ifndef _Included_com_zhuoting_health_util_Crc16Util
#define _Included_com_zhuoting_health_util_Crc16Util
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zhuoting_health_util_Crc16Util
 * Method:    makeCRC
 * Signature: ([BI)B
 */
JNIEXPORT jbyte JNICALL Java_com_zhuoting_health_util_Crc16Util_makeCRC
  (JNIEnv *env, jobject obj, jbyteArray array, jint jint1){

    jbyte *buffer = env->GetByteArrayElements(array,0);
    jsize  jsize1 = env->GetArrayLength(array);

    uint8_t  CRC_8 = 0;
    jbyte CRC_count,i;
    uint8_t cmd_buf[jsize1];
    for (int i = 0; i < jsize1; ++i) {
        cmd_buf[i] = *(buffer+i);
    }


    env->ReleaseByteArrayElements(array,buffer,0);
    for(CRC_count=0;CRC_count < jsize1;CRC_count++){
        for(i=0;i<8;i++){
            if(((CRC_8 ^ cmd_buf[CRC_count])&0x01)){
                CRC_8 ^= 0x18;
                CRC_8 >>= 1;
                CRC_8 |= 0x80;
            }
            else{
                CRC_8 >>= 1;
            }
            cmd_buf[CRC_count] >>= 1;
        }
    }

    return CRC_8;

}

#ifdef __cplusplus
}
#endif
#endif
